### ISSUE TITLE
unexpected cppcheck score

### ISSUE THREAD

**Issue by frederic-mahe** [adrianzap/softwipe#10]
while testing swarm, I noticed that:
```
 --- Running: CPPCHECK --- 
Total weighted Cppcheck warning rate: 0.0 (0/6884)
Detailled results have been written into softwipe_cppcheck_results.txt
Cppcheck Score: 9.2/10
```
cppcheck returns zero warnings and `softwipe_cppcheck_results.txt` is empty. Nonetheless, the score is 9.2, and not 10.0 has one would expect. Either the warning rate is not really zero, and some warnings are not logged (an independent cppcheck run reports 4 errors), or there is something wrong with the cppcheck score.

**Comment by Angtft** [comment]
Thank you, cppcheck scoring should be working as intended now.
