### ISSUE TITLE
Feature request: allow -x to take a file

### ISSUE THREAD

**Issue by josephwb** [adrianzap/softwipe#14]
I have a lot of directories I want to ignore. Could `-x` (or `-X`, maybe?) take a file listing files/directories to ignore? Ideally this would be one per line rather than a comma separated list (like with `x`). It is just a bit cumbersome to write these anew with each repeated test.

**Comment by Angtft** [comment]
Thank you for the suggestion, now it is possible to provide such a file via -X.
